### ISSUE TITLE
Enhance selector syntax.

### ISSUE THREAD

**Issue by shinima** [shinima/temme#2]
- [x] Change filter syntax from `:` to `|`
- [x] Support for pseudo-class like `:root`, `:first-child`
- [x] Support multiple selectors at root level.
- [x] Support for filter arguments, e.x. `$foo|split(',')|slice(0, 10)`.
- [x] Support for JavaScript comment syntax within selecotr.
- [x] Add support for empty selector whose result is always null.
- [x] Add support for value assignment, e.x., `$a = 'abc'`.
- [x] Add support for JavaScript literals, which includes null, boolean, numeric, string and RegExp.
- [x] Add support for using JS literals as filter arguments or as the right part of assignments.
- [x] Allow `;` to be selector seprator.
- [x] Refactor content capture syntax.
- [x] Change children selector brackets from `()` to `{}`.
- [x] Use css.pegjs to enhance grammar.
  - [x] Add support for universal element selector `*`.
  - [x] Add support for css combinator syntax which includes `>` , `+` and `~`.
  - [x] Add support for all attribute operators which includes `=`, `~=`, `|=`, `*=`, `^=`, `$=`.
  - [x] Add tests
- [x] Add support for multiple attribute qualifiers in one pair of brackets..
- [x] Add support for customized content function.

**Comment by j-greig** [comment]
How would you capture the URL to the background image from the below? (without the ?w=720 if possible!)

`        <div style="background-image: url(https://client.imgix.net/photo-006-3x2.jpg?w=720)" class="image"></div>
`

**Comment by shinima** [comment]
You can use `div[style=$|match(/https:.*\.jpg/)|first];` to capture the required string. Use `String#match` and regular expression to capture the image url.
