### ISSUE TITLE
建议新增scss语法和对象合并支持

### ISSUE THREAD

**Issue by cjd6568358** [shinima/temme#22]
类似于：
form .mainbox.viewthread@list{
        .postauthor@@author{
            cite a[id^=userinfo]{$name};
            p:nth-of-type(1){$level};
        }
        .postcontent{$content|html}
    }

output:
[
                {
                    author: { name: "111", level: "222" },
                    content: "fdjsfkfdf"
                }
            ]

**Comment by shinima** [comment]
@cjd6568358  可以提供一个完整的 HTML 片段么，我看一下。

**Comment by cjd6568358** [comment]
@shinima 
<li class="post" v-for="(post,i) of postList" :key="i">
                    <div class="post-author">
                        <span>{{post.authorName}}</span>
                        <span>{{post.authorLevel}}</span>
                    </div>
                    <div class="post-content" v-html="post.content">

                    </div>
                </li>

我想把authorName和authorLevel合并到author里，但是现在不支持，还有我想用scss语法。像.postauthor@@author{.a{$a;.b{$b}}} 这种语法是我想要的 但是现在不支持

**Comment by shinima** [comment]
做数据转换的话，可以使用[内联过滤器](https://github.com/shinima/temme/blob/master/readme-zh.md#%E5%86%85%E8%81%94%E5%AE%9A%E4%B9%89%E7%9A%84%E8%BF%87%E6%BB%A4%E5%99%A8)

scss 语法我去看一下再说。

**Comment by cjd6568358** [comment]
@shinima scss语法简化了选择器代码，而且数据结构会更清晰。
过滤器filter pack 支持对象合并，我去看下。
不过我个人还是觉得用scss语法来表现对象会更加清晰

**Comment by cjd6568358** [comment]
@shinima 看了一下 pack满足不了我的需求，原因是 
`.postcontent .postinfo@info|pack{
            strong{$postFloor};
            find('小',$postTime, '只看该作者')
        }`

非数组的情况下info对象如何定义？？？

**Comment by shinima** [comment]
@cjd6568358 这里报错是因为 find 是 content function，只能用在 content 中，而你直接把它当作了子选择器。改成这样就可以了：
![image](https://user-images.githubusercontent.com/5550931/38770021-013ab4f6-403f-11e8-8528-35e19b757bb7.png)

数据转换的问题，一般来说总是可以通过过滤器来实现的，内置的 pack 用来合并数组，如果无法满足要求的话，可以自己定义 inline filter 的。例如 [这个例子](https://temme.js.org/?example=github-issues) 里定义了 `url` 过滤器，可以用来根据 `baseUrl` 将相对 url 转换为完整的完整，例如把 `'/facebook/react/issues/11146'` 转换为 `'https://github.com/facebook/react/issues/11146'`

SCSS 语法这方面我还是不太明白，可以说一下具体的语法么？ 其实 temme 的语法应该已经挺高级了，支持嵌套的数组捕获，可以用来抓取复杂的 JSON 数据，例如[这个例子](https://temme.js.org/?example=tmall-reviews-Chinese) 中选择器一次性抓取了商品的所有评价数据。

**Comment by cjd6568358** [comment]
@shinima  你这里的@info 是针对数组的定义，但是我这里不是数组

**Comment by shinima** [comment]
@cjd6568358  我写了个简单的例子 https://runkit.com/shinima/5ad22372344e8a0012947948
你也在 runkit 写一个吧，不然感觉说不明白……

**Comment by cjd6568358** [comment]
@shinima  了解了。原来@和pack同时使用是可以封装成一个对象。之前我一直是单独用的@ 我以为@只能用在数组上

**Comment by shinima** [comment]
@cjd6568358  对的，@ 和 pack 需要配合一起用才能抓取类似 `{ author: { name: "111", level: "222" } }` 这样的数据。

temme 不支持类似 SCSS 的嵌套选择器，主要原因是语法解析问题。花括号 `{ ... }` 在 temme 中的功能目前有两个：
1. 用于 content：例如  `div{$text}` 用来选取节点的文本
2. 用于 子选择器，例如 `.parent@foo { .child-1{$a}; .child-2{$b} }`，子选择器需要放在花括号内

目前判断花括号是第一种还是第二种情况，只需要判断花括号之前是否存在 `@` 符号即可。

如果再添加嵌套选择器的功能的话，例如 `.ancester { .parent { .child{$xxx} } }`，那么花括号就又会多一个新的功能，花括号的含义就会很难判断。 所以，temme 里头用「@ 和 pack 配合」的方式来代替 类SCSS 的嵌套选择器。
