### ISSUE TITLE
逻辑判断

### ISSUE THREAD

**Issue by Dassiy** [shinima/temme#28]
你好，如果有一个类似如这样的html片段，内容不同，如何抓取这个list呢
能提供一下思路吗，感谢(･ω･)ﾉ

> <ul>
      <li class="t"><p>2132</p></li>
      <li class="t"><p>2132</p></li>
      <li class="p"><img></img></li>
      <li class="f"><h2><h2><p></p></li>
<ul>

**Comment by shinima** [comment]
你的 html 片段太简单了……  不是特别明白你想要抓取什么内容 @ @ 

我稍微修改了你的片段，可以看一下图中中的效果：

从 `li.t` 中抓取数字  `li.t @numberList {  &{$|Number};  };`
从 `li.p` 中图片  `li.p @imgList {  img[src=$]; };`
从 `li.f` 抓取文本 `li.f {$text};`

![image](https://user-images.githubusercontent.com/5550931/40874834-449546a6-66a7-11e8-81ef-87e40901641f.png)

**Comment by Dassiy** [comment]
2333，就是这样，开始我是想着在一个循环中处理所有数据，想复杂了
Thanks♪(･ω･)ﾉ
