### ISSUE TITLE
:first-child

### ISSUE THREAD

**Issue by chinacourt** [shinima/temme#38]
关于:first-child无法使用   希望可以得到一个解决方案   例如出现

```html
<div class="left">
  <h3>北京市</h3>
  <p>已接入<em class="data-margin-s">23</em>家</p>
  <p>未接入<em class="data-margin-s">0</em>家</p>
  <p>累计直播<em class="data-margin-b">1449</em>件</p>
</div>
```

需要得到`已接入量`和`未接入量`

**Comment by shinima** [comment]
`:first-child` 我测试了一下是正确的，在这个例子我觉得你应该用的是 `:first-of-type`。

其实这里用 [`:contains`](https://api.jquery.com/contains-selector/) 这个选择器更方便一些：

![image](https://user-images.githubusercontent.com/5550931/43644839-adf46e88-9762-11e8-8870-d35da342ab80.png)
