### ISSUE TITLE
Support Lodash filters in the CLI?

### ISSUE THREAD

**Issue by chocolateboy** [shinima/temme#47]
It would be great if we could use [Lodash](https://lodash.com/) [functions](https://devdocs.io/lodash/) as filters rather than (or in addition to) the current builtins, which are a useful but limited subset of the functionality available in Lodash.

I realise they can be added when using temme as a library, but that doesn't help with the CLI tool and requires anyone who wants to add those filters to write their own CLI frontend.

Several CLI tools use Lodash to enhance and extend the standard library e.g.:

- https://github.com/daxelrod/jowl
- https://github.com/FGRibreau/jq.node
- https://github.com/fritx/jayin
- https://github.com/sodiumjoe/lobar

**Comment by shinima** [comment]
I think using lodash functions as filter would be great. However, there is one major problem -- temme can only parse *JavaScript literals* while "lodash filters" requires *complex* arguments. For example, [`sortBy(collection, iteratees)`](https://lodash.com/docs/#sortBy) requires `iteratees` a function, which is not a literal value and cannot be parsed by temme.

If you want process the output of temme, you can pipe the output from temme to jq, e.g. `cat a.html | temme some-selector | jq xxxx`. 

Or save the temme-selector in a file and use that file in the CLI, so that you can define some customized filters to process data. For example...

```bash
echo 'div { $foo; }' > a.temme
temme a.temme "<div class=foo>hello</div>"
# output:  {"foo":"hello"}
```

**Comment by chocolateboy** [comment]
> temme can only parse *simple JavaScript literals* while "lodash filters" requires *complex* arguments.

Ah, fair enough. That makes sense.

> Or save the temme-selector in a file and use that file in the CLI

Thanks. I'll do that.

---

One thing that might be worth considering is some kind of `import` or `require` statement that can pull in a JavaScript module which can interact with the library to add custom filters e.g.:

```javascript
// movies.temme
import "filters.mjs";
```

```javascript
// movies.temme
require("filters.js");
```


\- and/or a command-line option to do this (like `-r`/`--require` in node/ruby etc.). The module could export a function which is passed the temme exports e.g.: 

```JavaScript
// filters.js

module.exports = function (temme) {
    temme.defineFilter(...)
}
```

Or possibly:

```JavaScript
// filters.mjs

export default function ({ defineFilter }) { ... }
```

This could then be invoked with e.g.:

```bash
$ temme -r filters.js -s <selector-expression> -i <html-expression>
$ temme -r filters.mjs -S <selector-file> -I <html-file>
```

As you can see, the options would probably need to be made more explicit to accommodate this, but I'd actually prefer that anyway.

Closing this, thanks (but I'm happy to raise a new issue for the `require`/`--require` proposal — or discuss it here — if there's any interest).

By the way, thanks for temme! It's the best DSL for [extracting structured data](https://github.com/dbohdan/structured-text-tools#xml-html) from unstructured documents I think I've ever used, and I've tried (and even written :-) quite a few [over the years](http://perladvent.org/2003/5th/) :+1:
